// packages/renderer/src/layout/PageHelp.vue
<script lang="ts">
import { defineComponent, onMounted } from 'vue'
const { getCurrentWindow } = window.require('@electron/remote')

export default defineComponent({
  setup() {
    const handleHideClick = (_e: any) => {
      getCurrentWindow().close()
    }

    onMounted(() => {
      setTimeout(() => {
        document.title = '小白羊帮助文档'
      }, 1000)
      setTimeout(() => {
        document.title = '小白羊帮助文档'
      }, 10000)
    })
    return { handleHideClick }
  }
})
</script>

<template>
  <a-layout style="height: 100vh; background: #f2f4f7" draggable="false">
    <a-layout-header id="xbyhead" draggable="false">
      <div id="xbyhead2" class="q-electron-drag">
        <div class="title">阿里云盘小白羊版</div>
        <div class="flexauto"></div>

        <a-button type="text" tabindex="-1" title="关闭 Alt+F4" @click="handleHideClick">
          <i class="iconfont iconclose"></i>
        </a-button>
      </div>
    </a-layout-header>
    <a-layout-content style="height: calc(100vh - 42px); padding-top: 8px; background: #f2f4f7">
      <div className="doc-preview" id="doc-preview" style="width: 100%; height: 100%">
        <Webview style="width: 100%; height: 100%" src="https://github.com/liupan1890/aliyunpan/wiki"></Webview>
      </div>
    </a-layout-content>
  </a-layout>
</template>

<style></style>

// alixbyelectron v3/src/renderer/pages/window/pagehelp.tsx
import SettingLog from '@/setting/settinglog'
import { Button, Layout } from 'antd'
import React from 'react'
import '../dark.css'
import '../index.css'
import '../pageleft.css'
const { Header, Content } = Layout

class PageHelp extends React.Component {
  constructor(props: any) {
    super(props)
    this.state = { isfull: false }
  }

  componentDidCatch(error: Error, info: any) {
    try {
      SettingLog.mSaveLog('danger', 'PageHelp' + (error.message || ''))
      if (error.stack) SettingLog.mSaveLog('danger', error.stack)
    } catch {}
  }
  componentDidMount() {
    setTimeout(() => {
      document.title = '小白羊帮助文档'
    }, 1000)
  }
  handleMinClick = () => {
    window.Electron.remote.getCurrentWindow().minimize()
  }
  handleMaxClick = () => {
    let win = window.Electron.remote.getCurrentWindow()
    if (win.isMaximized()) win.restore()
    else win.maximize()
  }
  handleHideClick = () => {
    window.Electron.remote.getCurrentWindow().close()
  }

  render() {
    return (
      <Layout className="root" draggable="false" style={{ background: '#f2f4f7' }}>
        <Header id="header" className="tophead" draggable="false">
          <div className="tophead2 q-electron-drag">
            <Button type="text">
              <i className="iconfont iconfile-file"></i>
            </Button>
            <div className="title">小白羊</div>
            <div className="flexauto">
              <div className="titlename">帮助文档</div>
            </div>

            <Button type="text" onClick={this.handleMinClick} title="最小化">
              <i className="iconfont iconzuixiaohua"></i>
            </Button>
            <Button type="text" onClick={this.handleMaxClick} title="最大化">
              <i className="iconfont iconfullscreen"></i>
            </Button>
            <Button type="text" onClick={this.handleHideClick} title="关闭">
              <i className="iconfont iconclose"></i>
            </Button>
          </div>
        </Header>
        <Layout draggable="false">
          <Content id="content" style={{ paddingTop: '8px', background: '#f2f4f7' }}>
            <div className="doc-preview" id="doc-preview" style={{ width: '100%', height: '100%' }}>
              <webview style={{ width: '100%', height: '100%' }} src="https://www.yuque.com/liupan1890/xiaobaiyang"></webview>
            </div>
          </Content>
        </Layout>
      </Layout>
    )
  }
}

export default PageHelp
