// alixbyelectron v3/src/renderer/pages/pan/creatnewdirmodal.tsx
import AliFile from '@/aliapi/file'
import AliFileCmd from '@/aliapi/filecmd'
import SettingLog from '@/setting/settinglog'
import SettingPan from '@/setting/settingpan'
import { ClearFileName } from '@/store/aria2c'
import PanDAL from '@/store/pandal'
import PanStore from '@/store/panstore'

import UserDAL from '@/store/userdal'
import { Input, message, Modal } from 'antd'
import React from 'react'

let _ShowCreatNewDirModal = false
export function ShowCreatNewDirModal(type: string, driveid: string, parentdirid: string, callback: any) {
  if (_ShowCreatNewDirModal) return
  _ShowCreatNewDirModal = true
  setTimeout(() => {
    _ShowCreatNewDirModal = false
  }, 500)
  const userID = UserDAL.QueryUserID()
  if (!userID) {
    message.info('请先登录一个阿里云盘账号')
    return
  }

  const modal = Modal.info({
    closable: true,
    centered: true,
    className: 'dialogmodal creatfoldermodal',
    icon: undefined,
    autoFocusButton: undefined,
    width: '80vw',
    style: { maxWidth: '440px', paddingBottom: '0' }
  })

  modal.update({
    title: '新建文件夹',
    content: <CreatNewDir type={type} driveid={driveid} parentdirid={parentdirid} callback={callback} modal={modal} />
  })
}

class CreatNewDir extends React.Component<{ type: string; driveid: string; parentdirid: string; callback: any; modal: { destroy: () => void; update: (configUpdate: any) => void } }, { loading: boolean; isIndex: boolean; dirname: string }> {
  constructor(props: any) {
    super(props)
    let dirname = ''
    let isIndex = false
    if (this.props.type == 'newdatefolder') {
      const date = new Date(Date.now())
      const y = date.getFullYear().toString()
      let m: number | string = date.getMonth() + 1
      m = m < 10 ? '0' + m.toString() : m.toString()
      let d: number | string = date.getDate()
      d = d < 10 ? '0' + d.toString() : d.toString()
      let h: number | string = date.getHours()
      h = h < 10 ? '0' + h.toString() : h.toString()
      let minute: number | string = date.getMinutes()
      minute = minute < 10 ? '0' + minute.toString() : minute.toString()
      let second: number | string = date.getSeconds()
      second = second < 10 ? '0' + second.toString() : second.toString()

      dirname = SettingPan.uiTimeFolderFormate.replace(/yyyy/g, y).replace(/MM/g, m).replace(/dd/g, d).replace(/HH/g, h).replace(/mm/g, minute).replace(/ss/g, second)
      if (SettingPan.uiTimeFolderFormate.indexOf('#') >= 0) {
        isIndex = true
        dirname = dirname.replace(/\#{1,}/g, function (val) {
          return SettingPan.uiTimeFolderIndex.toString().padStart(val.length, '0')
        })
      }
    }
    this.state = { loading: false, dirname, isIndex }
  }
  componentDidCatch(error: Error, info: any) {
    try {
      SettingLog.mSaveLog('danger', 'ShareLinkInput' + (error.message || ''))
      if (error.stack) SettingLog.mSaveLog('danger', error.stack)
    } catch {}
  }

  componentDidMount() {}
  componentWillUnmount() {
    this.setState = (state, callback) => {
      return
    }
  }

  handleCreatFolder = (newname: any) => {
    if (!newname) return
    if (typeof newname != 'string') return
    newname = newname.replace(/[<>\:"\\\|\?\*]+/g, '')
    newname = newname.replace(/[\f\n\r\t\v]/g, '')
    while (newname.endsWith(' ') || newname.endsWith('.')) newname = newname.substring(0, newname.length - 1)
    newname = newname.trim()
    if (!newname) return
    const token = UserDAL.GetUserToken(UserDAL.QueryUserID())
    if (!token || !token.access_token) {
      message.error('新建文件夹失败 账号失效，操作取消')
      return
    }
    const dir = PanStore.GetDir(this.props.driveid, this.props.parentdirid)
    if (!dir.file_id) {
      message.error('新建文件夹失败 父文件夹错误')
      return
    }

    AliFileCmd.ApiCreatNewForder(token.user_id, dir.drive_id, dir.file_id, newname)
      .then((data) => {
        if (data == undefined) message.error('新建文件夹 失败')
        else if (data == 'QuotaExhausted.Drive') message.error('新建文件夹失败：网盘空间已满')
        else {
          message.success('新建文件夹 成功')
          if (this.state.isIndex) SettingPan.mSaveUiTimeFolderIndex(SettingPan.uiTimeFolderIndex + 1)
          if (PanDAL.QuerySelectDir().file_id == this.props.parentdirid) {
            //刷新父文件夹
            window.getDvaApp()._store.dispatch({ type: 'treedir/aSelectDir', drive_id: '', file_id: 'refresh', force: true })
          } else {
            //在复制移动到窗口里创建，进调用强制刷新缓存
            return PanDAL.GetDirFileList(token.user_id, dir.drive_id, dir.file_id, true)
          }
        }
      })
      .catch((e: any) => {
        message.error('新建文件夹 失败 ' + (e.message || ''))
      })
      .then(() => {
        this.props.modal.destroy()
        if (this.props.callback) this.props.callback()
      })
  }

  inputRef = React.createRef<Input>()
  render() {
    return (
      <div>
        <div className="settingrow">
          <Input.Search ref={this.inputRef} defaultValue={this.state.dirname} enterButton="创建" autoFocus onKeyDown={(e) => e.stopPropagation()} onSearch={this.handleCreatFolder} />
        </div>
        <div className="settingrow">
          <span className="oporg">注：</span>文件夹名不要有特殊字符：<span className="opblue">{' < > : * ? \\ / \' " '}</span>
          <br />
          <br />
        </div>
      </div>
    )
  }
}

// src/renderer/pan/topbtns/CreatNewDirModal.vue
<script lang="ts">
import AliFileCmd from '../../aliapi/filecmd'
import { usePanTreeStore, useSettingStore } from '../../store'
import message from '../../utils/message'
import { modalCloseAll } from '../../utils/modal'
import { CheckFileName, ClearFileName } from '../../utils/filehelper'
import { defineComponent, ref, reactive, PropType } from 'vue'
import PanDAL from '../pandal'

export default defineComponent({
  props: {
    visible: {
      type: Boolean,
      required: true
    },
    dirtype: {
      type: String,
      required: true
    },
    parentdirid: {
      type: String
    },
    callback: {
      type: Function as PropType<(newdirid: string) => void>
    }
  },
  setup(props) {
    const okLoading = ref(false)
    const formRef = ref()

    const form = reactive({
      dirName: '',
      dirIndex: 1
    })
    const handleOpen = () => {
      setTimeout(() => {
        document.getElementById('CreatNewDirInput')?.focus()
      }, 200)

      if (props.dirtype == 'datefolder') {
        let dirName = ''
        let dirIndex = 1

        const date = new Date(Date.now())
        const y = date.getFullYear().toString()
        let m: number | string = date.getMonth() + 1
        m = m < 10 ? '0' + m.toString() : m.toString()
        let d: number | string = date.getDate()
        d = d < 10 ? '0' + d.toString() : d.toString()
        let h: number | string = date.getHours()
        h = h < 10 ? '0' + h.toString() : h.toString()
        let minute: number | string = date.getMinutes()
        minute = minute < 10 ? '0' + minute.toString() : minute.toString()
        let second: number | string = date.getSeconds()
        second = second < 10 ? '0' + second.toString() : second.toString()

        const settingStore = useSettingStore()
        dirName = settingStore.uiTimeFolderFormate.replace(/yyyy/gi, y).replace(/MM/g, m).replace(/dd/gi, d).replace(/HH/gi, h).replace(/mm/g, minute).replace(/ss/gi, second)
        if (settingStore.uiTimeFolderFormate.indexOf('#') >= 0) {
          dirIndex = settingStore.uiTimeFolderIndex
          dirName = dirName.replace(/#{1,}/g, function (val) {
            return dirIndex.toString().padStart(val.length, '0')
          })
        }
        form.dirName = dirName
        form.dirIndex = dirIndex
      } else {
        form.dirName = ''
        form.dirIndex = 1
      }
    }

    const handleClose = () => {
      
      if (okLoading.value) okLoading.value = false
      formRef.value.resetFields()
    }

    const rules = [
      { required: true, message: '文件夹名必填' },
      { minLength: 1, message: '文件夹名不能为空' },
      { maxLength: 100, message: '文件夹名太长(100)' },
      {
        validator: (value: string, cb: any) => {
          const chk = CheckFileName(value)
          if (chk) cb('文件夹名' + chk)
        }
      }
    ]

    return { okLoading, form, formRef, handleOpen, handleClose, rules }
  },
  methods: {
    handleHide() {
      modalCloseAll()
    },
    handleOK() {
      this.formRef.validate((data: any) => {
        if (data) return 

        const pantreeStore = usePanTreeStore()
        if (!pantreeStore.user_id || !pantreeStore.drive_id || !pantreeStore.selectDir.file_id) {
          message.error('新建文件夹失败 父文件夹错误')
          return
        }

        const newName = ClearFileName(this.form.dirName)
        if (!newName) {
          message.error('新建文件夹失败 文件夹名不能为空')
          return
        }

        this.okLoading = true
        let newdirid = ''
        AliFileCmd.ApiCreatNewForder(pantreeStore.user_id, pantreeStore.drive_id, this.parentdirid || pantreeStore.selectDir.file_id, newName)
          .then((data) => {
            if (data.error) message.error('新建文件夹 失败' + data.error)
            else {
              newdirid = data.file_id
              message.success('新建文件夹 成功')
              if (this.form.dirIndex) useSettingStore().updateStore({ uiTimeFolderIndex: this.form.dirIndex + 1 })
              if (!this.parentdirid || pantreeStore.selectDir.file_id == this.parentdirid) {
                
                PanDAL.aReLoadOneDirToShow('', 'refresh', false)
              } else {
                
                return PanDAL.GetDirFileList(pantreeStore.user_id, pantreeStore.drive_id, this.parentdirid, '')
              }
            }
          })
          .catch((err: any) => {
            message.error('新建文件夹 失败 ' + (err.message || ''))
          })
          .then(() => {
            modalCloseAll()
            if (this.callback) this.callback(newdirid)
          })
      })
    }
  }
})
</script>

<template>
  <a-modal :visible="visible" modal-class="modalclass" :footer="false" :unmount-on-close="true" :mask-closable="false" @cancel="handleHide" @before-open="handleOpen" @close="handleClose">
    <template #title>
      <span class="modaltitle">新建文件夹</span>
    </template>
    <div class="modalbody" style="width: 440px">
      <a-form ref="formRef" :model="form" layout="vertical">
        <a-form-item field="dirName" :rules="rules">
          <template #label>文件夹名：<span class="opblue" style="margin-left: 16px; font-size: 12px"> 不要有特殊字符 &lt; > : * ? \\ / \' " </span> </template>
          <a-input v-model.trim="form.dirName" placeholder="例如：新建文件夹" allow-clear :input-attrs="{ id: 'CreatNewDirInput', autofocus: 'autofocus' }" />
        </a-form-item>
      </a-form>
      <br />
    </div>
    <div class="modalfoot">
      <a-button v-if="false" type="outline" size="small" @click="handleHide">批量创建</a-button>
      <div style="flex-grow: 1"></div>
      <a-button v-if="!okLoading" type="outline" size="small" @click="handleHide">取消</a-button>
      <a-button type="primary" size="small" :loading="okLoading" @click="handleOK">创建</a-button>
    </div>
  </a-modal>
</template>

<style></style>
