// alixbyelectron v3/src/renderer/pages/pan/creatnewfilemodal.tsx
import AliFile from '@/aliapi/file'
import AliUploadMem from '@/aliapi/uploadmem'
import SettingLog from '@/setting/settinglog'
import PanDAL from '@/store/pandal'
import PanStore from '@/store/panstore'

import UserDAL from '@/store/userdal'
import { Button, Form, FormInstance, Input, message, Modal } from 'antd'
import React from 'react'

let _ShowCreatNewFileModal = false
export function ShowCreatNewFileModal(driveid: string, parentdirid: string) {
  if (_ShowCreatNewFileModal) return
  _ShowCreatNewFileModal = true
  setTimeout(() => {
    _ShowCreatNewFileModal = false
  }, 500)
  const userID = UserDAL.QueryUserID()
  if (!userID) {
    message.info('请先登录一个阿里云盘账号')
    return
  }
  const modal = Modal.info({
    closable: true,
    centered: true,
    className: 'dialogmodal creatfilemodal',
    icon: undefined,
    autoFocusButton: undefined,
    width: '80vw',
    style: { maxWidth: '740px', paddingBottom: '0', height: '80vh' }
  })

  modal.update({
    title: '新建文件',
    content: <CreatNewFile userID={userID} driveid={driveid} parentdirid={parentdirid} modal={modal} />
  })
}

class CreatNewFile extends React.Component<{ userID: string; driveid: string; parentdirid: string; modal: { destroy: () => void; update: (configUpdate: any) => void } }, { loading: boolean }> {
  constructor(props: any) {
    super(props)

    this.state = { loading: false }
  }
  componentDidCatch(error: Error, info: any) {
    try {
      SettingLog.mSaveLog('danger', 'ShareLinkInput' + (error.message || ''))
      if (error.stack) SettingLog.mSaveLog('danger', error.stack)
    } catch {}
  }

  componentDidMount() {}
  componentWillUnmount() {
    this.setState = (state, callback) => {
      return
    }
  }

  handleOk = () => {
    let filename = (this.formRef.current?.getFieldValue('filename') as string) || ''
    filename = filename.trim()
    let filecontent = (this.formRef.current?.getFieldValue('filecontent') as string) || ''
    filecontent = filecontent.trim()

    const token = UserDAL.GetUserToken(this.props.userID)
    if (!token || !token.access_token) {
      message.error('新建文件失败 账号失效，操作取消')
      return
    }

    const dir = PanStore.GetDir(this.props.driveid, this.props.parentdirid)
    if (!dir.file_id) {
      message.error('新建文件失败 父文件夹错误')
      return
    }
    AliUploadMem.UploadMem(this.props.userID, dir.drive_id, dir.file_id, filename, filecontent)
      .then((data) => {
        if (data && data == 'success') {
          window.getDvaApp()._store.dispatch({ type: 'treedir/aSelectDir', drive_id: '', file_id: 'refresh', force: true })
          message.success('新建文件 成功')
          this.props.modal.destroy()
        } else {
          message.error('新建文件 失败 ' + data)
        }
      })
      .catch((e: any) => {
        message.error('新建文件 失败 ' + (e.message || ''))
      })
  }

  formRef = React.createRef<FormInstance>()
  render() {
    return (
      <>
        <Form ref={this.formRef} layout="vertical" preserve={false} name="form_in_modal">
          <Form.Item
            name="filename"
            label={
              <>
                文件名
                <span className="opblue" style={{ marginLeft: '16px', fontSize: '12px' }}>
                  {'不要有特殊字符 < > : * ? \\ / \' " '}
                </span>
              </>
            }>
            <Input autoFocus allowClear onKeyDown={(e) => e.stopPropagation()} placeholder="例如：19日干饭计划.txt" />
          </Form.Item>
          <Form.Item name="filecontent" label="文件内容">
            <Input.TextArea id="form_in_modal_filecontent" onKeyDown={(e) => e.stopPropagation()} showCount />
          </Form.Item>
        </Form>
        <div className="flex flexnoauto">
          <div className="flexauto"></div>
          <Button key="back" onClick={(e) => this.props.modal.destroy()}>
            取消
          </Button>
          <div style={{ margin: '0 6px' }}></div>
          <Button type="primary" loading={this.state.loading} onClick={this.handleOk}>
            创建
          </Button>
        </div>
      </>
    )
  }
}

// src/renderer/pan/topbtns/CreatNewFileModal.vue
<script lang="ts">
import AliUploadMem from '../../aliapi/uploadmem'
import { usePanTreeStore } from '../../store'
import message from '../../utils/message'
import { modalCloseAll } from '../../utils/modal'
import { CheckFileName, ClearFileName } from '../../utils/filehelper'
import { defineComponent, ref, reactive } from 'vue'
import PanDAL from '../pandal'

export default defineComponent({
  props: {
    visible: {
      type: Boolean,
      required: true
    }
  },
  setup(props) {
    const okLoading = ref(false)
    const formRef = ref()
    const form = reactive({
      filename: '',
      filecontext: ''
    })
    const handleOpen = () => {
      setTimeout(() => {
        const autofocus = document.getElementById('CreatNewFileInput')
        if (autofocus) autofocus.focus()
      }, 200)

      form.filename = ''
      form.filecontext = ''
    }

    const handleClose = () => {
      
      if (okLoading.value) okLoading.value = false
      formRef.value.resetFields()
    }

    const rules = [
      { required: true, message: '文件名必填' },
      { minLength: 1, message: '文件名不能为空' },
      { maxLength: 100, message: '文件名太长(100)' },
      {
        validator: (value: string, cb: any) => {
          let chk = CheckFileName(value)
          if (chk) cb('文件名' + chk)
        }
      }
    ]

    return { okLoading, form, formRef, handleOpen, handleClose, rules }
  },
  methods: {
    handleHide() {
      modalCloseAll()
    },
    handleOK() {
      this.formRef.validate((data: any) => {
        if (data) return 

        const pantreeStore = usePanTreeStore()
        if (!pantreeStore.user_id || !pantreeStore.drive_id || !pantreeStore.selectDir.file_id) {
          message.error('新建文件失败 父文件夹错误')
          return
        }

        let newname = ClearFileName(this.form.filename)
        if (!newname) {
          message.error('新建文件失败 文件名不能为空')
          return
        }

        this.okLoading = true
        AliUploadMem.UploadMem(pantreeStore.user_id, pantreeStore.drive_id, pantreeStore.selectDir.file_id, newname, this.form.filecontext)
          .then((data) => {
            this.okLoading = false
            if (data && data == 'success') {
              
              PanDAL.aReLoadOneDirToShow('', 'refresh', false)
              message.success('新建文件 成功')
              modalCloseAll()
            } else {
              message.error('新建文件 失败 ' + data)
            }
          })
          .catch((err: any) => {
            this.okLoading = false
            message.error('新建文件 失败 ' + (err.message || ''))
          })
      })
    }
  }
})
</script>

<template>
  <a-modal :visible="visible" modal-class="modalclass" @cancel="handleHide" @close="handleClose" @before-open="handleOpen" :footer="false" :unmount-on-close="true" :mask-closable="false">
    <template #title>
      <span class="modaltitle">新建文本文件</span>
    </template>
    <div class="modalbody" style="width: 80vw; max-width: 860px; height: calc(80vh - 100px)">
      <a-form ref="formRef" :model="form" layout="vertical" style="height: 100%; display: flex">
        <a-form-item field="filename" :rules="rules">
          <template #label>文件名：<span class="opblue" style="margin-left: 16px; font-size: 12px"> 不要有特殊字符 &lt; > : * ? \\ / \' " </span> </template>
          <a-input v-model.trim="form.filename" placeholder="例如：今天工作计划.txt" allow-clear :input-attrs="{ id: 'CreatNewFileInput', autofocus: 'autofocus' }" />
        </a-form-item>
        <a-form-item field="filecontext" label="文件内容：" class="textareafill">
          <a-textarea v-model="form.filecontext" placeholder="粘贴内容" show-word-limit @keydown="(e) => e.stopPropagation()" />
        </a-form-item>
      </a-form>
    </div>
    <div class="modalfoot">
      <div style="flex-grow: 1"></div>
      <a-button v-if="!okLoading" type="outline" size="small" @click="handleHide">取消</a-button>
      <a-button type="primary" size="small" :loading="okLoading" @click="handleOK">创建</a-button>
    </div>
  </a-modal>
</template>

<style>
.textareafill {
  flex-grow: 1;
  display: flex !important;
  flex-direction: column;
}
.textareafill .arco-form-item-wrapper-col {
  flex-grow: 1;
}
.textareafill .arco-form-item-wrapper-col .arco-form-item-content-wrapper,
.textareafill .arco-form-item-wrapper-col .arco-form-item-content,
.textareafill .arco-form-item-wrapper-col .arco-textarea-wrapper,
.textareafill .arco-form-item-wrapper-col .arco-textarea {
  height: 100%;
}
</style>
